apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: my-service
  namespace: nginxdemo
spec:
  ports:
  - name: 5678-8080
    port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
    team: devops
  type: NodePort
